### ISSUE TITLE
Recommended versions of dependencies

### ISSUE THREAD

**Issue by carroarmato0** [mpalmer/lvmsync#40]
I've installed lvmsync together with treetop and git-version-bump via  gem install.

Running into this issue:

<pre>
~# lvmsync -h
/usr/lib/ruby/site_ruby/1.8/rubygems/specification.rb:538:in `method_missing': undefined method `lib_dirs_glob' for #<Gem::Specification:0x7f2d832854f8> (NoMethodError)
	from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.13.3/lib/git-version-bump.rb:39:in `caller_gemspec'
	from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.13.3/lib/git-version-bump.rb:38:in `each'
	from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.13.3/lib/git-version-bump.rb:38:in `caller_gemspec'
	from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.13.3/lib/git-version-bump.rb:90:in `version'
	from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.13.3/lib/git-version-bump/version.rb:2
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
	from /usr/lib/ruby/gems/1.8/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.13.3/lib/git-version-bump.rb:234
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
	from /usr/lib/ruby/gems/1.8/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/lib/ruby/gems/1.8/gems/lvmsync-3.3.0/bin/lvmsync:22
	from /usr/bin/lvmsync:19:in `load'
	from /usr/bin/lvmsync:19
</pre>

Could this have something to do with the version of git-version-bump?   Could you list the version which has been tested against?

**Comment by mpalmer** [comment]
I have listed the versions of `git-version-bump` that `lvmsync` has been tested against, in the gem metadata (`~> 0.10`).  The actual problem here is that you're running a version of Rubygems that doesn't have the `lib_dirs_glob` method implemented.  Since it's a relatively straightforward change, I've just released 0.13.4 of `git-version-bump` that removes the use of `lib_dirs_glob` and instead implements the same functionality using features of Rubygems that have been available since (at least) 2004.  If your Rubygems is older than that... well, you're on your own from there.

I don't personally use Ruby 1.8 anywhere myself any more, so I can't guarantee that everything will work with such old versions of Ruby, but I try to maintain compatibility where it's feasible, when people report problems.
