### ISSUE TITLE
Self-contained installation

### ISSUE THREAD

**Issue by guestisp** [mpalmer/lvmsync#50]
Not all servers has ruby installed (ie: XenServer)
Having lvmsync in a self-contained mode would be very useful

**Comment by mpalmer** [comment]
Sorry, but I'm not going to do an all-in-one bundled installer for such a small script. There are plenty of ways to easily install Ruby from source (such as `ruby-build`, `rvm`, etc etc) which you can use to get a Ruby installation onto a system that lacks a decent package management system of its own.

**Comment by guestisp** [comment]
Any change to get this working with ruby 1.8.5 ?
I have a XenServer 5.5 with some VM that I would like to migrate, but the only ruby available is 1.8.5 and some gems requires ruby 1.8.7

**Comment by mpalmer** [comment]
I'd accept a patch for git-version-bump (and lvmsync) that made it work on 1.8.5, as long as it didn't make the code *too* hideous (or broken).  I'm not in a position to work that up myself, though, since 1.8.5 is so old there's no definition for it in ruby-build (my preferred "get me a random Ruby" tool).

**Comment by guestisp** [comment]
I'm not a ruby programmer, i have no idea on how to fix this.
I'm just trying to use lvmsync on a very old XenServer (based on CentOS 5.5) that has ruby 1.8.5

**Comment by guestisp** [comment]
BTW, i've tried with ruby-build but on XenServer Dom0 I don't have any build utils thus i'm unable to build a new version

**Comment by mpalmer** [comment]
> I'm not a ruby programmer, i have no idea on how to fix this.

Well, as Wesley says, "then we are at an impasse".  I'm afraid don't have the time or inclination to dig into supporting a Ruby version that is now so old I don't remember when it was superceded.  Presumably you could find someone with ancient Ruby knowledge on a freelancers site to dig into it for you.

> I don't have any build utils

Since XenServer is based on CentOS 5.5, presumably you could install the relevant packages from CentOS to get a build environment going?  That's almost certainly going to be a better solution than Ruby archaeology anyway.

**Comment by guestisp** [comment]
You are totally right, but having a build environment in Dom0 requires an update to glibc from Base repo of CentOS. I'm not sure to update glibc directly from Centos, this could lead to issues with XenServer
